// Generated by CoffeeScript 1.6.2
var assert, e, jy, pluginDir, request, root, toType;

pluginDir = __dirname + '/../';

toType = function(obj) {
  return {}.toString.call(obj).match(/\s([a-zA-Z]+)/)[1].toLowerCase();
};

assert = require('chai').assert;

request = require('request');

try {
  jy = require('jellyjs');
} catch (_error) {
  e = _error;
  root = __dirname + '/../../../../';
  jy = require("" + root + "/index.js");
}

describe('#Plugin::output', function() {
  return it('Should work on File entities', function(cb) {
    var jelly;

    jelly = new jy.Jelly();
    return jelly.boot({
      directory: "" + __dirname + "/demo",
      packagePlugins: ['template'],
      folderPlugins: [
        {
          name: 'output',
          directory: pluginDir
        }
      ],
      localRequire: function(elm, cb) {
        try {
          return cb(null, require.resolve(elm));
        } catch (_error) {
          e = _error;
          return cb(e);
        }
      }
    }, function(err) {
      return cb(err);
    });
  });
});
