// Generated by CoffeeScript 1.6.2
var assert, e, fs, jy, path, pluginDir, request, root, shell, toType;

pluginDir = __dirname + '/../';

toType = function(obj) {
  return {}.toString.call(obj).match(/\s([a-zA-Z]+)/)[1].toLowerCase();
};

assert = require('chai').assert;

request = require('request');

shell = require('shelljs');

fs = require('fs');

path = require('path');

try {
  jy = require('jellyjs');
} catch (_error) {
  e = _error;
  root = __dirname + '/../../../../';
  jy = require("" + root + "/index.js");
}

describe('#Plugin::output', function() {
  it('Should work on File entities', function(cb) {
    var jelly;

    shell.rm('-rf', "" + __dirname + "/demo/public");
    jelly = new jy.Jelly();
    return jelly.boot({
      directory: "" + __dirname + "/demo",
      packagePlugins: ['template'],
      folderPlugins: [
        {
          name: 'output',
          directory: pluginDir
        }
      ],
      localRequire: function(elm, cb) {
        try {
          cb(null, require.resolve(elm));
          return cb = function() {};
        } catch (_error) {
          e = _error;
          cb(e);
          return cb = function() {};
        }
      }
    }, function(err) {
      if (err) {
        cb(err);
        cb = function() {};
        return;
      }
      return fs.readFile("" + __dirname + "/demo/public/module1-file1.tpl", function(err, data) {
        if (err) {
          cb(new Error("The generated extension does not work as expected: " + err.message));
          cb = function() {};
          return;
        }
        try {
          assert.equal(data + '', 'TPL TEST', 'The file content should be equal to the original content');
          cb();
          return cb = function() {};
        } catch (_error) {
          e = _error;
          cb(e);
          return cb = function() {};
        }
      });
    });
  });
  it('Should expose a "file-list" sharedObject', function(cb) {
    var jelly;

    shell.rm('-rf', "" + __dirname + "/demo/public");
    jelly = new jy.Jelly();
    return jelly.boot({
      directory: "" + __dirname + "/demo",
      packagePlugins: ['template'],
      folderPlugins: [
        {
          name: 'output',
          directory: pluginDir
        }
      ],
      localRequire: function(elm, cb) {
        try {
          cb(null, require.resolve(elm));
          return cb = function() {};
        } catch (_error) {
          e = _error;
          cb(e);
          return cb = function() {};
        }
      }
    }, function(err) {
      var content;

      if (err) {
        cb(err);
        cb = function() {};
        return;
      }
      try {
        content = jelly.getSharedObjectManager().getObject('output', 'file-list');
        assert.equal(toType(content), 'object');
        content = content.getCurrentContent();
        assert.equal(toType(content), 'array');
        assert.equal(content.length, 1);
        assert.equal(path.normalize(content[0].absoluteFilename), path.normalize("" + __dirname + "/demo/public/module1-file1.tpl"));
        assert.equal(content[0].filename, 'module1-file1.tpl');
        assert.equal(toType(content[0].obj), 'object');
        assert.equal(content[0].obj.File, true);
        assert.equal(content[0].obj.getId(), 'module1-file1.tpl');
        return cb();
      } catch (_error) {
        e = _error;
        return cb(e);
      }
    });
  });
  return it('Should expose a method to use with templates', function(cb) {
    var jelly;

    shell.rm('-rf', "" + __dirname + "/demoModule/public");
    jelly = new jy.Jelly();
    return jelly.boot({
      directory: "" + __dirname + "/demoModule",
      packagePlugins: ['template'],
      folderPlugins: [
        {
          name: 'output',
          directory: pluginDir
        }
      ],
      localRequire: function(elm, cb) {
        try {
          cb(null, require.resolve(elm));
          return cb = function() {};
        } catch (_error) {
          e = _error;
          cb(e);
          return cb = function() {};
        }
      }
    }, function(err) {
      return cb();
    });
  });
});
