// Generated by CoffeeScript 1.6.2
var express;

express = require('express');

module.exports = {
  load: function(cb) {
    return cb();
  },
  oncall: function(onj, params, cb) {
    return cb();
  },
  unload: function(cb) {
    return cb();
  }
};
