// Generated by CoffeeScript 1.6.2
module.exports = {
  load: function(cb) {
    return cb();
  },
  oncall: function(obj, params, cb) {
    if (obj.File === true) {
      cb();
      cb = function() {};
      return;
    }
    cb();
    return cb = function() {};
  },
  unload: function(cb) {
    return cb();
  }
};
